name = "Newb X LMI - Alpha"
version = [0, 16, 0]
min_supported_mc_version = [1, 26, 10]
description = '''
§c%w
§7- Enhanced Newb Shader to improve vanilla looks! V16-Alpha
%v
§3https://github.com/zan4re27/newb-x-lmi/
''' # %w = patch warning, %v = version
authors = ["devendrn", "zan4re27"]
url = "https://github.com/zan4re27/newb-x-lmi/"
uuid = "f431a500-9f9f-42a2-ae57-f28a6e850f93" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2026 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog and wave effects
'''

[[subpack]]
define = "NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog effect
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No wave effects
'''

[[subpack]]
define = "NO_SHOOTING_STARS"
materials = ["Sky"]
description = '''
Will Disable The Shooting Stars if you don't like it :)
'''

[[subpack]]
define = "RAINBOW"
materials = ["Sky"]
description = '''
Rainbow!
'''

[[subpack]]
define = "GALAXY"
materials = ["Sky"]
description = '''
Galaxy Skies
'''

[[subpack]]
define = "GROUND_REFLECTION"
materials = ["RenderChunk"]
description = '''
Fake Ground Reflection
'''

[[subpack]]
define = "CAVE_VISION"
materials = ["Actor", "ActorGlint", "ItemInHandColor", "ItemInHandColorGlint", "ItemInHandTextured", "RenderChunk"]
description = '''
Cave Vision (Brighter Cave)
'''

[[subpack]]
define = "MULTILAYERED_ROUNDED_CLOUDS"
materials = ["Clouds"]
description = '''
Default Cloud Multilayered
'''

[[subpack]]
define = "VOLUMETRIC_CLOUDS"
materials = ["Clouds"]
description = '''
Volumetric/Reaalistic Clouds
'''

[[subpack]]
define = "SOFT_CLOUDS"
materials = ["Clouds"]
description = '''
Soft Clouds
'''

[[subpack]]
define = "VANILLA_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
Better Vanilla Clouds
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
