name: build

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      subversion:
        description: 'Sub-version (eg: 46)'
        required: true
        type: string
      platform:
        description: 'platform'
        required: true
        default: 'All'
        type: choice
        options:
        - Android
        - Windows
        - IOS
        - Merged
        - All

env:
  SUBVERSION_OPT: ${{ inputs.subversion && format('-v {0}', inputs.subversion) || '' }}

jobs:
  windows:
    runs-on: windows-2022
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.platform == 'Windows' || inputs.platform == 'All' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-win-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        .\build.bat setup
        .\build.bat pack -p windows ${{ env.SUBVERSION_OPT }} --no-zip
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-lmi-windows
        path: ./build/pack-windows
  android:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.platform == 'Android' || inputs.platform == 'All' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-linux-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        ./build.sh setup
        ./build.sh pack -p android ${{ env.SUBVERSION_OPT }} --no-zip
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-lmi-android
        path: ./build/pack-android
  ios:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.platform == 'IOS' || inputs.platform == 'All' }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-linux-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        ./build.sh setup
        ./build.sh pack -p ios ${{ env.SUBVERSION_OPT }} --no-zip
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-lmi-ios
        path: ./build/pack-ios
  merged:
    runs-on: windows-2022
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.platform == 'Merged' || inputs.platform == 'All' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-win-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        .\build.bat setup
        .\build.bat pack -p merged ${{ env.SUBVERSION_OPT }} --no-zip
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-lmi-merged
        path: ./build/pack-merged